language: java
jdk:
    - oraclejdk8
after_success:
- python <(curl -s https://raw.githubusercontent.com/lordOfSputnik/sputnik-test/master/sputnik-ci.py)

env:
  global:
#  paste your api_key here
#  - secure: